<?php
define("SYSTEM_PATH","system/");
define("CORE_PATH",SYSTEM_PATH."core/");
define("STATIC_PATH",SYSTEM_PATH."static/");
define("HTML_PATH",STATIC_PATH."html/");
define("CSS_PATH",STATIC_PATH."css/");
define("JS_PATH",STATIC_PATH."js/");
define("IMG_PATH",STATIC_PATH."img/");
define("LANG_PATH",STATIC_PATH."language/");
define("MEDIA_PATH",STATIC_PATH."media/");