<?php
define("PATH", "./");
define("DEBUG", "yes");
define("SYSTEM_PATH", PATH . "system/");
define("CORE_PATH", SYSTEM_PATH . "core/");
define("STATIC_PATH", SYSTEM_PATH . "static/");
define("HTML_PATH", STATIC_PATH . "html/");
define("CSS_PATH", STATIC_PATH . "css/");
define("JS_PATH", STATIC_PATH . "js/");
define("IMG_PATH", STATIC_PATH . "img/");
define("LANG_PATH", STATIC_PATH . "language/");
define("MEDIA_PATH", STATIC_PATH . "media/");
define("AUDIO_PATH", STATIC_PATH . "audio/");
define("FONT_PATH", STATIC_PATH . "fonts/");
define("CONFIG_PATH", PATH . "config/");
define("FILE_DB_PATH", SYSTEM_PATH . "data/");
define("DATA_PATH", PATH . "data/");
define("CACHE_PATH",SYSTEM_PATH."cache/");
define("SECRET", "20J1YYDS");
define("FILE_DB_POSTFIX", "db");
